version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.0.0
    steps:
      - checkout
      # Checkout the local package as a sibling directory
      - run:
          name: Checkout Local Package
          command: |
            cd ..
            git clone https://github.com/cdrice26/statmaster
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Link Local Package
          command: |
            cd ../statmaster
            npm install
            npm link
            cd ../statsview
            npm link statmaster
      - run:
          name: Typecheck
          command: npm run dev
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
