version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/rust:1.75-node
    steps:
      - checkout
      - run:
          name: Install wasm-pack
          command: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run:
          name: Build WASM Package
          command: |
            cd ../statmaster  # adjust path as needed
            wasm-pack build --platform web
            npm link
      - run:
          name: Return to project directory
          command: cd statsview
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Link WASM Package
          command: npm link statmaster
      - run:
          name: Typecheck
          command: npm run dev
      - run:
          name: Run Tests
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist
      - store_test_results:
          path: test-results

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
